### ISSUE TITLE
[bug][Windows Server] Issue with QT wallet not syncing (Out of Sync) with error message

### ISSUE THREAD

**Issue by jpass022** [ioncoincore/ion-v4#111]
**Describe the bug**
QT is showing blockchain is 1 to 2 hours behind even though Block count is current and getting pop-up warning about time not being set correctly. Time is set correctly.

**To Reproduce**
1. Start QT.

**Expected behavior**
Expect to see time is current with current block count.

**Screenshots**
![screenshot v3 1 01 02 08 19](https://user-images.githubusercontent.com/5889788/52491340-83e8d200-2b8c-11e9-8a10-fe915825b9ac.png)

**Desktop (please complete the following information):**
 - OS: Proxmox VM Windows Server 2012
 - Browser [na]
 - Version [ion 3.1.1.01]

**Smartphone (please complete the following information):**
 - na

**Additional context**
not self compiled, downloaded from https://github.com/ionomy/ion/releases.
https://github.com/ionomy/ion/releases/download/v3.1.01/ion-3.1.01-win64-setup-unsigned.exe

**Comment by cevap** [comment]
thanks @jpass022 for submitting, please go through this checklist:

- ***You should not enable host time synchronization on a virtual machine that is configured as a domain controller. You should instead use an external source for time synchronization.***
- You might also want to consider using the NTP pool found here:
  - http://www.pool.ntp.org/en/
  For the us it would be:
    - http://www.pool.ntp.org/zone/us
    - 0.us.pool.ntp.org
    - 1.us.pool.ntp.org
    - 2.us.pool.ntp.org
    - 3.us.pool.ntp.org
- use any other external NTP server
- check your policies
- [have you set your time correctly?](http://social.technet.microsoft.com/Forums/windowsserver/en-US/e2702910-a95f-4a82-8aa7-3891a80db56f/configuring-hyperv-time-syncing-with-a-member-server-as-host-and-the-dc-in-a-vm)
- **Disable host time synchronization when running a domain controller inside a virtual machine**
  You should not enable host time synchronization on a virtual machine that is configured as a domain controller. You should instead use an external source for time synchronization.
  http://technet.microsoft.com/en-us/library/cc708332(v=ws.10).aspx

**Comment by jpass022** [comment]
My VM is not a domain controller and is in the same time zone as local. 
I tried with 'Use local time for RTC' both on and off and it made no difference.
![image](https://user-images.githubusercontent.com/5889788/52493198-7af9ff80-2b90-11e9-9db0-dace88be2a45.png)

Issue happens immediately as soon as block count reaches current. 

DEVs responded promptly to my issue.

**Comment by jpass022** [comment]
Problem is definitely related to being ran in a Server 2012 VM, works fine in Native Server 2012 environment.

**Comment by cevap** [comment]
use external NTP, it should resolve your issue.

**Comment by jpass022** [comment]
Changed time server in windows from time.windows.com to time-a.nist.gov and error is gone...

**Comment by cevap** [comment]
thanks @jpass022 for confirm that proposed solution resolved the issue, feel free to reopen this issue if there is a need for it.
