### ISSUE TITLE
[Snap][Build][Linux]Arm32 segfaults due to use of gcc5 on build

### ISSUE THREAD

**Issue by ckti** [ioncoincore/ion-v4#115]
Armbian 32 (using ssh -X)
X11 connection rejected because of wrong authentication.
qt.qpa.screen: QXcbConnection: Could not connect to display localhost:10.0
Could not connect to any X display.
--- running /snap/ioncore/current/bin/ion-qt does not do this ---

Armbian 32 First Run (native X-Windows)
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory

Armbian 32 Second (and subsequent) Runs (native X-Windows)
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
Segmentation fault <-- compiling with gcc5 causes this there's an old issue for this
snap list
Name     Version    Rev   Tracking  Publisher   Notes
core     16-2.37.1  6351  stable    canonical✓  core
ioncore  3.1.00     368   stable    ioncoin     -
^-- old version of ioncore (and yes i removed and re-instaled)
![version](https://user-images.githubusercontent.com/7046769/52522607-7a8c6200-2c7f-11e9-8ec6-9e0572e2c43f.png)

**Comment by ckti** [comment]
Got snap to use arm-linux-gnuebihf-gXX-4.8, will transpose this to my snap and build.

**Comment by cevap** [comment]
fixed in #143 , closing this issue
