### ISSUE TITLE
Update snapcraft to use gcc-8 on bionic

### ISSUE THREAD

**Issue by ckti** [ioncoincore/ion-v4#119]
Segfaults occur in arm32 binaries compiled with gcc-5 in xenial. (See issue #115 as well)

**Comment by ckti** [comment]
Have it working now for github -> launchpad build -> binaries -> snap store.  investigating how we can do github -> snap store -> binaries using base: core18 and bionic

**Comment by ckti** [comment]
here's what i've found so far with snapcraft -> launchpad -> snap store
snaps ARE updated on snap store and snap install installs the correct client but they show as failed at https://build.snapcraft.io/user/<user\>/<snap\> this is what i'm trying to get to the bottom of right now.  seems the git clone process doesn't like the double sources and defaults to launchpad binary
...just a theory, getting a git pull error when pulling the repo: "Channel stable/launchpad-buildd for snapcraft is closed; temporarily forwarding to stable."

**Comment by ckti** [comment]
Yes it works with a clean snap store entry

**Comment by ckti** [comment]
one last test to put update-alternatives stanza before the depends make

**Comment by ckti** [comment]
one last test to put update-alternatives stanza before the depends make

**Comment by ckti** [comment]
XKB patch not working on arm32

**Comment by ckti** [comment]
patch patches correctly /snap/.../bin/ion-qt does not error out like this

**Comment by ckti** [comment]
The error comes in here
_**16:20:21.834330 stat64("/usr/share/X11/xkb", 0xbebed3f0) = -1 ENOENT (No such file or directory)**_  
**^-- file exists on host system --^**
16:20:21.834494 stat64("/root/snap/from-lp/13/.xkb", 0xbebed3f0) = -1 ENOENT (No such file or directory)
16:20:21.834664 write(2, "xkbcommon: ERROR: ", 18xkbcommon: ERROR: ) = 18
16:20:21.834834 write(2, "failed to add default include pa"..., 54failed to add default include path /usr/share/X11/xkb
) = 54
16:20:21.834999 clock_gettime(CLOCK_MONOTONIC, {2183498, 690997039}) = 0
16:20:21.835169 openat(AT_FDCWD, "/dev/tty", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 5
16:20:21.835337 fcntl64(5, F_SETFD, FD_CLOEXEC) = 0
16:20:21.835486 close(5)                = 0
16:20:21.835633 write(2, "Qt: Failed to create XKB context"..., 34Qt: Failed to create XKB context!
) = 34
16:20:21.835798 write(2, "Use QT_XKB_CONFIG_ROOT environme"..., 294Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .

**Comment by ckti** [comment]
Building arm32 package natively with snap
...
Same XKB Error

**Comment by cevap** [comment]
fixed in #143 , closing this issue
