### ISSUE TITLE
[xION][MAC OS][Minting]  "xION seed used to mint this xION is not the same as currently hold in the wallet"

### ISSUE THREAD

**Issue by mdpfeiffer** [ioncoincore/ion-v4#123]
**Situation:**
I get this message when I click on xION Control in the Privacy panel on Mac Qt.

"xION seed used to mint this xION is not the same as currently hold in the wallet"

![screen shot 2019-02-28 at 2 52 26 pm](https://user-images.githubusercontent.com/1129489/53594289-8e353500-3b68-11e9-9423-3cd44738a4d3.jpg)

**Problem:**
The messages makes me think that if my wallet.dat gets corrupted I would lose my xION because I don't have the corresponding seed.

**Context:**
When I close the Qt, then re-open it, the xION is still there and spendable. I have been able to successfully spend it. 

The command `getxionseed` appears to allow me to export the seed.

The command `setxionseed` appears to allow me to import another seed.

**Questions:**
Is it possible that when I tested these functions that I "set" a new xION seed, but the wallet continues to mint xION with a different seed? If so, wouldn't that mean that a single wallet is using two different seeds at once, but only one will be returned with the 'getxionseed` command?

Is my xION recoverable from the wallet.dat if it was minted using a different seed than the one held in the wallet? 

If there's a risk of losing my xION when this message displays, is there a way to re-set the primary, active seed?

Does the wallet.dat retain both the original and active seed used for minting xION and the imported secondary seed? If so, then in cases where more than one seed is present shouldn't the `getxionseed` command issue all active seeds?

**_Edit:_**
Let me put this a different way. I assume that saving my xION seed in a secure location will mean I can always recover any xION that was minted with that seed. But if I don't know what that seed is, and if I can't instruct the wallet to print it, then the inaccessibility of the xION seed defeats the purpose.

My assumption about the deterministic seed is that it is somewhat analogous to a private key for an ION address, with a major difference. The privkey corresponds only with transactions for a particular public address in the wallet, while the deterministic xION seed corresponds to every xION mint performed with that seed or encoded with that seed. 

I'm laying out my assumptions to make it easy for respondents to correct me if I'm wrong.

Software Version:
Ion Core version v3.1.01 (64-bit)
downloaded from https://github.com/ioncoincore/ion/releases
Running on Mac OS 10.14

**Comment by mdpfeiffer** [comment]
There's a typo in the message:
I suggest changing "hold" to "held"

"xION seed used to mint this xION is not the same as currently _**hold**_ in the wallet"

**Comment by raid12345678** [comment]
@mdpfeiffer  I will have one of our Devs look into this issue. Should have more information for you on Monday or sooner. Thank you for your submission.

**Comment by mdpfeiffer** [comment]
**Additional information**

I've continued to mint and spend xION with this wallet. The "Is Spendable" column shows a variety of messages. It's possible that more than one message could be true at once, but only one would be displayed. May need to consider showing multiple messages if they apply so the user can figure out what the problem is.

"Is Spendable" messages I've seen include:

"Yes"
"The xION seed used to mint this xION is not the same as currently hold in the wallet."
"Needs 1 more mints added to network"

![screen shot 2019-03-06 at 10 28 21 am](https://user-images.githubusercontent.com/1129489/53976159-79aaec80-40d4-11e9-9157-4ec54103ab5e.jpg)


Sometimes I have found that I cannot spend xION when the displayed message is  "The xION seed used to mint this xION is not the same as currently hold in the wallet." But that may be because of a different underlying problem. The real problem may be that new xION of the desired nomination may need to be minted on the network before my existing xION can be spent. The reason I think that's true is when I've waited some time, the xION becomes selectable and spendable. I imagine it's spendable now because someone else minted xION in the same denomination after me.

Also, I have found that the "different seed" message sometimes does not show up at all when I mint xION. I guess that could mean that the primary seed was used for minting, not the secondary seed, but it's not clear.

----

**xION Control selection errors**
 
![screen shot 2019-03-07 at 12 25 18 pm](https://user-images.githubusercontent.com/1129489/53976204-8deee980-40d4-11e9-947d-4ef86ecdefd3.jpg)

You can see in the screenshot above that if I click the box next to the disclosure triangle, all of the "50" denominated xION are selected with grey check marks. But the Quantity selected shows zero, and the total value selected shows zero.

When I "deselect all," I cannot select any of the individual xION denominations shown in coin control. The checkbox is non-responsive.

I think this may simply be a display error. The select all function is misleading because it makes it look like the xION is selectable when it isn't. And the select all display is inconsistent with the individual selection display.

----

**"Needs 1 more mints added to network"**
I think this message means, "The xION protocol doesn't allow you to spend xION until an additional xION unit of the same denomination is minted." In that case, there's nothing the user can do but wait, or mint more xION from their own wallet of the same denomination they want to spend.

An alternative message might be:
"Not spendable until one more xION unit of the same denomination is minted on the network."

---

I realize these various errors may need to be reformatted as separate error tickets, but until I understand what the error messages mean, I'm not sure how to separate these related issues.

**Comment by AtomSmasher00** [comment]
I'm seeing this xION error as well. The denominations are not individually selectable.

<img width="1011" alt="Screen Shot 2019-03-11 at 10 29 21 AM" src="https://user-images.githubusercontent.com/16825821/54135890-ab7bc600-43e8-11e9-9567-575df3e59b1e.png">
<img width="1012" alt="Screen Shot 2019-03-11 at 10 29 44 AM" src="https://user-images.githubusercontent.com/16825821/54135895-af0f4d00-43e8-11e9-91f6-cbca7346a3ad.png">

**Comment by cevap** [comment]
thanks for supplying detailed report, I only miss your reports about how you tried to deal with it. I can assume that you tried to resync, but looking at those screnshots, I would assume that you played with importing/exporting zerocoin's and did not properly resync those changes or corrupted them. I can exclude in all cases, but here it was reported that you could spend your coins which would mean for me that they are spendable.

Now, where I could always reproduce this issue is if I import a seed in my wallet where I keep it using on some another one. This message is then correct as it tells you correctly that the seed which was used to mint this xION was probably on another wallet.

What you should do for troubleshooting beside resync, zapwallettxs etc.. is that you check commands in debug console (type help to show them) and there you will find all according commands which could help you, like:
- getarchivedzerocoin
- reconsiderzerocoins
- resetmintzerocoin
- resetspentzerocoin

use help for more info about those commands, however, in current case I do not see an error, especially as they are spendable and do warn you as addition that seed is not the same. 

I will close this issue with that, feel free to reopen if you think that issue still persists and that it is some bug/error. For explanation about how many confirmations etc.., we probably should update a wiki if there is no info about it, but as far as I remember there was, if there is no, I will add replies to asked questions to the wiki.
