### ISSUE TITLE
[GUI][HELP][MAC OS] getxionseed help text suggestion

### ISSUE THREAD

**Issue by mdpfeiffer** [ioncoincore/ion-v4#124]
When I type `help getxionseed` in the debug console on the Qt, the help text is confusing. I think the first line may be wrong:

> getxionseed Check archived xION list to see if any mints were added to the blockchain. Requires wallet passphrase to be set with walletpassphrase call. Result
> "seed" : s, (string) The deterministic xION seed. Examples
> > ion-cli getxionseed
> > curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getxionseed", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:12705/
> 

Maybe the help text should instead say: 

> "Returns the value of the wallet's deterministic xION seed."

Ion Core version v3.1.01 (64-bit)
downloaded from GitHub
running on Mac OS 10.14

**Comment by raid12345678** [comment]
@mdpfeiffer  Thank you for your submission one of your Devs will be looking into this issue

**Comment by ckti** [comment]
Have opened pull request #131 for this
