### ISSUE TITLE
[ERROR][MAC OS]Revise error message re: spending more than 5 xION inputs

### ISSUE THREAD

**Issue by mdpfeiffer** [ioncoincore/ion-v4#126]
![screen shot 2019-02-28 at 4 12 23 pm](https://user-images.githubusercontent.com/1129489/53598857-c68e4080-3b73-11e9-93bc-badd0cdf8d45.jpg)

When I try to spend more than 5 xION inputs, error message reads:

> "Failed to find coin set amongst held coins with less than maxNumber of Spends"

The message does not clearly tell the user what they did wrong, or what the maxNumber is.

Proposed error message:

> "You can only spend a maximum of 5 xION inputs at once. Please try the transaction again with a smaller amount. Clicking the "xION control" button will allow you to see xION denominations available for spending."

I don't know what "failed to find coin set" means, so I may be missing something important. If so, could you explain what the error message means?

Software Version:
Ion Core version v3.1.01 (64-bit)
downloaded from https://github.com/ioncoincore/ion/releases
Running on Mac OS 10.14

**Comment by raid12345678** [comment]
@mdpfeiffer  Thank you for your submission one of your Devs will be looking into this issue

**Comment by ckti** [comment]
Have opened pull request #132 for this

**Comment by ckti** [comment]
Have opened pull request #132 for this
