### ISSUE TITLE
[GUI][MAC OS] Coin Control window conceals the lowest transaction by default

### ISSUE THREAD

**Issue by mdpfeiffer** [ioncoincore/ion-v4#127]
**Problem:** 
The blue bar at the bottom of the Coin Control window obscures the last address on the list.

This is a problem when you have a longer list of addresses more transactions than the default window displays. There is a scrollbar on the right side of the panel, but scrolling down does not reveal the last address unless you expand the window manually.

The result can be that it looks like you are missing an entire address from your wallet. Of course, you can find it by reversing the sort functions, but the display problem is not obvious, so the solution is not obvious either.

**Examples:**
The first screenshot below shows the address ending with "kkg". It appears to be the last address on the list, but it is not. You can also see the blue scrollbar on the right. You would think you could adjust it by dragging it down, but even when dragged down to the lowest point, you still can't see the last address.

![screen shot 2019-02-28 at 3 43 04 pm](https://user-images.githubusercontent.com/1129489/53601546-4cad8580-3b7a-11e9-9de9-035343ddc46c.jpg)

This second screenshot shows the same window after manual expansion. If I drag the window size larger, there's no scrollbar on the right, and there's no blue bar blocking the view of the last address. You can see that below the address ending in "kkg" there is another address, as well.

![screen shot 2019-02-28 at 3 43 19 pm](https://user-images.githubusercontent.com/1129489/53601547-4cad8580-3b7a-11e9-9c35-bca533d4b3d2.jpg)

**Suggested solution:** 
Get rid of the blue bar at the bottom, or retain it as a border _below_ the last address. It may be necessary to make adjustments to the scroll bar function, as well.

Note:
The problem exist in Coin Control on both the Privacy Tab and the Send Tab.

Software Version:
Ion Core version v3.1.01 (64-bit)
downloaded from https://github.com/ioncoincore/ion/releases
Running on Mac OS 10.14

**Comment by raid12345678** [comment]
@mdpfeiffer  Thank you for your submission one of your Devs will be looking into this issue
