### ISSUE TITLE
[feature request] Add "activetime" to `getmasternodestatus` output

### ISSUE THREAD

**Issue by mdpfeiffer** [ioncoincore/ion-v4#133]
**Problem**
`getmasternodestatus` command returns helpful information, but a "status 4" message can be displayed even when there are problems that prevent the masternode from accruing activetime.

In my experience, the `activetime` metric is the definitive indicator for successfully configured and operational masternode.

**Feature Request**
Add 'activetime" display to 'getmasternodestatus` output.

**Additional Context**
Is there need for any additional community or dev team discussion about what else should be included in the output?

For example
**Currently ionomy platform** displays the following details when you click "View daemon data"

{
    "rank": 150
    "network": "ipv4",
    "txhash": "959b59b59b59b59b59b59b59b59b59b59b59b59ba",
    "outidx": 0,
    "pubkey": "03442586e79778b8989f0bgfhafasdfkljiou75023985092834095isldfjgk098",
    "status": "ENABLED",
    "addr": "iZzart9023fro7389bor80Olafjlkkmblkjlkjt8jztion",
    "version": 95702,
    "lastseen": 1501800592,
    "activetime": 170377,
    "lastpaid": 1001794600
}

Compare to: **ion-cli current output:**

{
  "txhash": "959b59b59b59b59b59b59b59b59b59b59b59b59ba",
  "outputidx": 0,
  "netaddr": "19.237.95.04:12700",
  "addr": "iZzart9023fro7389bor80Olafjlkkmblkjlkjt8jztion",
  "status": 4,
  "message": "Masternode successfully started"

**Comment by cevap** [comment]
Have you tried: `help listmasternodes`
Here is the output:
```
listmasternodes ( "filter" )

Get a ranked list of masternodes

Arguments:
1. "filter"    (string, optional) Filter search text. Partial match by txhash, status, or addr.

Result:
[
  {
    "rank": n,           (numeric) Masternode Rank (or 0 if not enabled)
    "txhash": "hash",    (string) Collateral transaction hash
    "outidx": n,         (numeric) Collateral transaction output index
    "pubkey": "key",   (string) Masternode public key used for message broadcasting
    "status": s,         (string) Status (ENABLED/EXPIRED/REMOVE/etc)
    "addr": "addr",      (string) Masternode ION address
    "version": v,        (numeric) Masternode protocol version
    "lastseen": ttt,     (numeric) The time in seconds since epoch (Jan 1 1970 GMT) of the last seen
    "activetime": ttt,   (numeric) The time in seconds since epoch (Jan 1 1970 GMT) masternode has been active
    "lastpaid": ttt,     (numeric) The time in seconds since epoch (Jan 1 1970 GMT) masternode was last paid
  }
  ,...
]

Examples:
> ion-cli listmasternodes 
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "listmasternodes", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:12705/
```

Ok, running now `listmasternodes` to get a list of all masternodes and will pick up any (by txhash, status, or addr) 
depending on what you choose, I assume you will want to choose it by address, I just picked any from the list:
```
listmasternodes ibGDgrjfN7twqUhpiFEqaFFx1Jw37R4e7d
```

Outputs:
```json
[
  {
    "rank": 118,
    "network": "ipv4",
    "txhash": "fbc7a8f90fee10c1bc7f3be85aecac0221786e6ae88eb683e650deab70cd2484",
    "outidx": 0,
    "pubkey": "0480fe8a369f01d4cfffd790742915b22df2b3fb43fea1392bbae06b150c042c9c2ee62d21daf88186633837de5ad47cd4ea4c67c03c763111768bfd701eca88cf",
    "status": "ENABLED",
    "addr": "ibGDgrjfN7twqUhpiFEqaFFx1Jw37R4e7d",
    "version": 95702,
    "lastseen": 1552722034,
    "activetime": 484380,
    "lastpaid": 1552694249
  }
]
```

as you can see, `"activetime": 484380`

**Comment by raid12345678** [comment]
The recommendation is to as follows.
Obsolete: "getmasternodestatus" to determine only if your masternode is Enable or Disabled
getmasternodestatus works only on a local hosted masternode 
Reason you might use this is: for those who neither know the address of their masternode, nor txid 
but you can easily find this information and get a better status.

recommended: "listmasternodes" to get details of your Masternode this includes Enables or Disabled.
can be on a remote server or local machine.
  listmasternode "your masternode addr" or "txhash"
