### ISSUE TITLE
[org][build][gitian] Test Environment for Software Testing (VMWare)

### ISSUE THREAD

**Issue by ioncoincore** [ioncoincore/ion-v4#16]
Create VM environments of most used **supported** operating systems for internal testing (current tests ref: https://github.com/ioncoincore/ion/issues/12)

**Comment by ckti** [comment]
I can create the ubuntu & fedora vms as i already have all the iso spins from building virtualbox machines

**Comment by ckti** [comment]
Ubuntu, Fedora, Centos & OpenSUSE VMs are now created, waiting for the last of the images to upload

**Comment by ckti** [comment]
Will shift some images around, WIll put OpenSUSE and CentOS on google drive to start with then see how much space is available on the disk on the transmission server
