### ISSUE TITLE
[Help] Splash screens

### ISSUE THREAD

**Issue by dkbay** [ioncoincore/ion-v4#175]
I made some splash screens for you guys 
But I couldn't figure out how to make a pull request sooo I made this issue instead...

![splash_regtest](https://user-images.githubusercontent.com/1548975/64299820-de0f1180-cf7a-11e9-8899-d6c345fe82b7.png)
![splash_testnet](https://user-images.githubusercontent.com/1548975/64299821-de0f1180-cf7a-11e9-8d5e-b0fd68bd0d67.png)
![splash](https://user-images.githubusercontent.com/1548975/64299822-de0f1180-cf7a-11e9-9306-826429a20501.png)
Zip:
[splash.zip](https://github.com/ioncoincore/ion/files/3576810/splash.zip)

**Comment by MitchellCash** [comment]
Thanks @dkbay! Nice work 👍

Could we just make some of the gray text that sits on the gray background lighter so we have a higher contrast ratio - it's hard to read right now, especially for people who may have any colour vision deficiency.

![Splash](https://user-images.githubusercontent.com/8009243/64352069-4a2d5c00-cff3-11e9-96d0-dfe2351ab476.png)

**Comment by dkbay** [comment]
Sure thing @MitchellCash! I'll probably fix it Sunday at some point I have some plans for the next few days 

I got another message from Wolverine too 
![image](https://user-images.githubusercontent.com/1548975/64367938-7956c400-d019-11e9-92cb-0359365d3a61.png)

**Comment by RdeWilde** [comment]
Isn't "the business of fun" the slogan for Ionomy? Where this is (just) ION.

**Comment by dkbay** [comment]
@RdeWilde Idk but that's none of my business (Got the joke?) I'm just making the current one prettier

**Comment by RdeWilde** [comment]
Hehe, that's fun

**Comment by MitchellCash** [comment]
@dkbay sorry I forgot you weren't opening a PR. I will fix the text colour once I get the updated imagery.

**Comment by dkbay** [comment]
@MitchellCash Made the background for the text light and fixed the stuff @ionwolverine mentioned so should be all good now like last time properly named files are in the Zip
![splash_testnet](https://user-images.githubusercontent.com/1548975/64647824-059e2800-d41a-11e9-9445-4f3be0dfa29d.png)
![splash](https://user-images.githubusercontent.com/1548975/64647825-059e2800-d41a-11e9-916f-9dad5c6d89c5.png)
![splash_regtest](https://user-images.githubusercontent.com/1548975/64647827-059e2800-d41a-11e9-844c-163a7ce6cb56.png)

Zip:
[splash.zip](https://github.com/ioncoincore/ion/files/3597577/splash.zip)
