### ISSUE TITLE
[randon issue][gitian][org][maintenance] missing keys (additionaly, new keys should be added)

### ISSUE THREAD

**Issue by ioncoincore** [ioncoincore/ion-v4#18]
additionaly, new keys should be added:
- [x] `6FC0DA39B9C70ED4F72C13FD4C29E79FFD989B4E` @Atomsmasher
- [x] `4629A11CF305F6B0580F73E92370B3FD71AFA1A8` @ceforce
- [x] `8DF801E04897084147DA70BB8E698F4907E09CA7` @ckti
- [x] `3BECF4903CDDDBE22476F3055E07DE13A8D009CB` @ionmy
- [x] `3D1CB36D4A9AFA1F61AAF9C32C40600694A44AB4` @kwwood

To be added missing keys from:
1. @ionstaff 
1. @adammatlack 
1. @raid12345678

_Originally posted by @ioncoincore in https://github.com/ioncoincore/ion/issue_comments#issuecomment-452589172_

**Comment by ckti** [comment]
That key for me is incorrect, should be 3CAF614CD0CEE28F0259A24F170FF5109E45AB6B
