### ISSUE TITLE
[testing][gitian]Test Report 3.1.99 Windows 10 x64

### ISSUE THREAD

**Issue by CeForce** [ioncoincore/ion-v4#29]
**Build:** v3.1.99 

**OS:** Windows 10 x64

**Features/Commands Tested:**
Basic send and receive functions
Create new address
import private keys
staking functions
masternode creation
masternode operation/staking

**Results:**
No issues encountered

**Feedback:**
None

**Comment by cevap** [comment]
can you add links to binaries to be used?

**Comment by raid12345678** [comment]
This is completed work Closing.
