### ISSUE TITLE
[docs]Definitions for new RPC commands required for release notes

### ISSUE THREAD

**Issue by CeForce** [ioncoincore/ion-v4#36]
I need some descriptions of the new RPC commands added in this release for the release notes.
Please briefly explain the function of the new commands (could also be used for -help entries on daemon)

`createmasternodebroadcast`

`decodemasternodebroadcast`

`relaymasternodebroadcast`

A new set of rpc commands masternodebroadcast to create masternode broadcast messages offline and relay them from online node later (messages expire in ~1 hour).

`getextendedbalance`

`listtransactionrecords`

`listrecordssinceblock`

**Comment by CeForce** [comment]
Additional defenitions, explainers for release notes required

`Initiated transition to bech32 address encoding`


`Fix checklocktimeverify unit tests`

**Comment by cevap** [comment]
we should update also wiki part: https://github.com/ioncoincore/ion/wiki/API-Calls-List
