### ISSUE TITLE
[bug] Proposal Icon in QT includes PIVX logo

### ISSUE THREAD

**Issue by bradinator** [ioncoincore/ion-v4#58]
**Describe the bug**
The proposal icon on left sidebar shows the "P" pivx logo

**To Reproduce**
1. View sidebar in QT

**Expected behavior**
Icon shouldn't have Pivx logo.  It could have ion logo, or be unbranded icon. 

**Desktop (please complete the following information):**
 - OS: Lunix Ubuntu 16.04
Ion Core version v3.1.00.0-97320ba-dirty (64-bit)

![536e5be88a50255668320e23f2a4df2a](https://user-images.githubusercontent.com/13177516/51682498-30339180-1fad-11e9-9e68-732276acb273.png)

**Comment by ckti** [comment]
Latest version of wallet v3.1.99.0-332ac71-dirty (64-bit) does not use this icon
![image](https://user-images.githubusercontent.com/7046769/51689582-e23f7d80-1fee-11e9-82df-bbb1b942c65c.png)
