### ISSUE TITLE
[org] Get timeline for marketing (spork dates, fork dates, features included)

### ISSUE THREAD

**Issue by CeForce** [ioncoincore/ion-v4#6]
I've started this task:

12:01 AM GMT Feb 1 - Must use new spork key (updated client)
12:01 AM GMT Feb 7 - Zerocoin 2 becomes Active
12:01 AM GMT Feb 7 - Reject old spork key

**Comment by ioncoincore** [comment]
JUST A TEST, I AM CLOSING; FEEL FREE TO REOPEN

**Comment by CeForce** [comment]
Updated: 

12:01 AM GMT Feb 1 - Must use new spork key (reccomended updated client date) Release date of this client.
12:01 AM GMT Feb 6 - Zerocoin goes into maintenance mode (cannot create new zerocoins at this time)
12:01 AM GMT Feb 7 - Zerocoin 2 becomes active (able to mint new zerocoins, and spend v1, v2)
12:01 AM GMT Feb 7 - Reject old spork key (required updated client date)
