### ISSUE TITLE
[testing]Test Report v3.1.00-beta1 local: Windows 10x64 remote: Ubuntu 16.04x64

### ISSUE THREAD

**Issue by j05eph2000** [ioncoincore/ion-v4#61]
Build:v3.1.00-beta1

OS:local: Windows 10x64 
     remote: Ubuntu 16.04x64 VPS server

Features/Commands Tested:
Sent coins to another address
Created a masternode and get mn rewards
Coin staking
Mint xion
Spent xion to ion

Results: 
All good
Feedback:
None

**Comment by cevap** [comment]
thanks for your test report
