### ISSUE TITLE
[feature request] Update zerocoin v2 start time to reflect new timline

### ISSUE THREAD

**Issue by CeForce** [ioncoincore/ion-v4#71]
As discussed at ion development meeting on 1.26.19 move the zerocoin v2 start time to Feb 10, 00:01 GMT

**Reject old Spork Key** 1549497601 (Feb 7, 12:01am GMT)
**Zerocoin V2 Start Timestamp:** 1549756860 (Feb 10, 12:01am GMT)

**Comment by cevap** [comment]
current values should reflect it, will close it, reopen please if there is a reason for that
