### ISSUE TITLE
[testing][windows][linux]Test Report v3.1.00-beta1 Windows 32 & 64 bit / Linux Daemon 64bit

### ISSUE THREAD

**Issue by XEOHASH** [ioncoincore/ion-v4#80]
Build: v3.1.00-beta1

OS: Windows 10

Features/Commands Tested:
1. Download, Launch & Sync
2. Test general options
3. Encrypt wallet, change passphrase, lock, unlock and backup wallet
4. Create new receive addresses with labels
5. Coin control functions, transactions and TX fees displays
6. ION Send & Receive 
7. xION Zerocoin Mint, Send & Receive 
8. Staking
9. Masternode setup with Linux Daemon 64-bit on Ubuntu 16.04 VPS

Results:
All wallet functions tested good! 

Feedback:
Please show all Local in-wallet TX that include Fee's!

**Comment by raid12345678** [comment]
@XEOHASH are you refering to your previous ticked about adding the TX that shows the fees? If so I can link that ticket to this ticket.

**Comment by XEOHASH** [comment]
Yes, when sending 20K to self...

**Comment by raid12345678** [comment]
I have added #60 to this ticket I will close out this test and @XEOHASH  your issue will live on in in that Github issue. Thank you for testing our wallets
