### ISSUE TITLE
[testing][windows]Test Report Win 10 64bit

### ISSUE THREAD

**Issue by korvasc** [ioncoincore/ion-v4#81]
Build: Ion Core version v3.1.00.0-97320ba (64-bit)

OS:Win 10 64Bit

Features/Commands Tested:
Download, Launch & Sync
Test general options
Encrypt wallet, change passphrase, lock, unlock and backup wallet
Create new receive addresses with labels
ION Send with Swift x & Receive
xION Zerocoin Mint, Send & Receive
Staking
Results:
All good
Feedback:
Wallet running for 3 days now no problems

**Comment by raid12345678** [comment]
Thank you for your testing!
