### ISSUE TITLE
[feature request]Query current list of automintaddresses 

### ISSUE THREAD

**Issue by FornaxA** [ioncoincore/ion-v4#90]
When a client creates an automintaddress, there currently is no easy way to retrieve that address, or to get an overview of currently existing automint addresses.
I'd propose to at least create an RPC command to retrieve those addresses.
Alternative solutions would be to tag addresses returned by other commands, such as listaddressgroupings, as automint addresses. However, I assume a user would mostly like to know what addresses can be used for autominting so he/she can send coins there, making a dedicated RPC call the more relevant option.

**Comment by cevap** [comment]
closed with #91
